---
abstract: 'Organize Data in Tables'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3617'
keywords:
  - art
  - ascii
  - asciiart
  - borders
  - table
  - text
  - unicode
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Table
provides:
  Text::Table:
    file: lib/Text/Table.pm
    version: 1.121
requires:
  Text::Aligner: 0.05
  strict: 0
  warnings: 0
resources:
  homepage: http://www.shlomifish.org/open-source/projects/docmake/
  license: http://www.opensource.org/licenses/bsd-license.php
  repository: https://github.com/shlomif/Text-Table
version: 1.121
