---
abstract: 'Organize Data in Tables'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::More: '0'
  blib: '1.01'
  constant: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, CPAN::Meta::Converter version 2.150010'
keywords:
  - art
  - ascii
  - asciiart
  - borders
  - table
  - text
  - unicode
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Table
provides:
  Text::Table:
    file: lib/Text/Table.pm
    version: '1.133'
requires:
  Carp: '0'
  List::Util: '0'
  Text::Aligner: '0'
  overload: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-Table
  repository: ssh://git@github.com:shlomif/Text-Table.git
version: '1.133'
