--- #YAML:1.0
name:                Text-Table
version:             1.114
abstract:            Organize Data in Tables
license:             ~
author:              
    - Anno Siegel (siegel@zrz.tu-berlin.de)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Text::Aligner:                 0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
